name: fluttiyomi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.8"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.0.1
  auto_route: ^5.0.3
  json_annotation: ^4.4.0
  dio: ^4.0.1
  expandable_text: 2.2.0
  pull_to_refresh: ^2.0.0
  visibility_detector: ^0.2.2
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.1
  path_provider: ^2.0.0
  path: ^1.8.0
  easy_debounce: ^2.0.2
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  flutter_form_builder: ^7.1.0
  form_builder_validators: ^7.4.0
  form_builder_extra_fields: ^7.1.0
  timeago: ^3.3.0
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  firebase_crashlytics: ^3.0.10
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  google_sign_in: ^5.4.3
  cloud_firestore: ^4.3.1
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  flutter_isolate: ^2.0.4
  flutter_animate: ^2.1.0
  riverpod_annotation: ^1.1.1
  riverpod_generator: ^1.1.1
  collection: ^1.16.0
  async: ^2.9.0
  fullscreen: ^1.0.3
  flutter_cache_manager: ^3.3.0
  workmanager: ^0.5.1
  flutter_local_notifications: ^13.0.0
  yaml: ^3.1.1
  html: ^0.15.1
  cache_manager: ^1.0.0+4

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  isar_generator: 3.0.5
  dart_code_metrics: ^5.4.0

# dependency_overrides:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/sources/readm.yml
    - assets/sources/mangajar.yml
    - assets/icons/library.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
