// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkMjFHgWcwB7ykQeoJME1hB7HSzauFtj0',
    appId: '1:235165685655:web:6a55398e6dc0b5d467d6d2',
    messagingSenderId: '235165685655',
    projectId: 'fluttiyomi',
    authDomain: 'fluttiyomi.firebaseapp.com',
    storageBucket: 'fluttiyomi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz2vvMSQ6Go289kjFV0m8o3IqXchvq2DM',
    appId: '1:235165685655:android:368c01daa6c2f8b467d6d2',
    messagingSenderId: '235165685655',
    projectId: 'fluttiyomi',
    storageBucket: 'fluttiyomi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaIqSqwfA6W3ee6wuCxGG0vHJo1J58wJM',
    appId: '1:235165685655:ios:1e5de70a1237cc6a67d6d2',
    messagingSenderId: '235165685655',
    projectId: 'fluttiyomi',
    storageBucket: 'fluttiyomi.appspot.com',
    androidClientId: '235165685655-i1otm6cq6s1blrd4j40lqcvjm21b55hu.apps.googleusercontent.com',
    iosClientId: '235165685655-l9i4a774u0r8s27g26bp16ao32k7npiq.apps.googleusercontent.com',
    iosBundleId: 'com.wardy484.fluttiyomi',
  );
}
